services:
  cookie_manager:
    build:
      context: ./services/cookie_manager
      dockerfile: Dockerfile
    container_name: cookie_manager
    restart: unless-stopped
    ports:
      - "8000:8000"  # FastAPI
      - "8080:8080"  # NoVNC
    env_file:
      - .env
    volumes:
      - ./services/cookie_manager/cookies.json:/app/cookies.json
    depends_on:
      - app_redis
    networks:
      - flipper_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  parser_cian:
    build:
      context: .  # Контекст - корень проекта
      dockerfile: ./services/parser_cian/Dockerfile
    container_name: parser_cian
    env_file:
      - .env
    volumes:
      - ./credentials.json:/app/credentials.json
    depends_on:
      cookie_manager:
        condition: service_healthy
    networks:
      - flipper_network
    profiles:
      - manual  # Запускается только вручную

  app_redis:
    image: redis:alpine
    container_name: app_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - flipper_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  flipper_network:
    driver: bridge

volumes: {}